--- #YAML:1.0
name:               POE-Component-ResourcePool
version:            0.04
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Clan:          0
    Moose:               0.37
    MooseX::POE:         0.205
    POE:                 0
    Set::Object:         1.20
    Test::use::ok:       0
    Tie::RefHash:        0
    Tie::RefHash::Weak:  0.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
